package internal

const (
	keywordAggregate = "AGGREGATE"
	keywordAll       = "ALL"
	keywordAny       = "ANY"
	keywordAs        = "AS"
	keywordAt        = "AT"
	keywordBackoff   = "BACKOFF"
	keywordCollect   = "COLLECT"
	keywordDispatch  = "DISPATCH"
	keywordDistinct  = "DISTINCT"
	keywordDo        = "DO"
	keywordEvent     = "EVENT"
	keywordEvery     = "EVERY"
	keywordExists    = "EXISTS"
	keywordFilter    = "FILTER"
	keywordFunc      = "FUNC"
	keywordFor       = "FOR"
	keywordIn        = "IN"
	keywordInto      = "INTO"
	keywordJitter    = "JITTER"
	keywordKeep      = "KEEP"
	keywordLeast     = "LEAST"
	keywordLet       = "LET"
	keywordLimit     = "LIMIT"
	keywordMatch     = "MATCH"
	keywordNone      = "NONE"
	keywordNot       = "NOT"
	keywordNull      = "NULL"
	keywordOptions   = "OPTIONS"
	keywordOr        = "OR"
	keywordQuery     = "QUERY"
	keywordReturn    = "RETURN"
	keywordSort      = "SORT"
	keywordStep      = "STEP"
	keywordThrow     = "THROW"
	keywordTimeout   = "TIMEOUT"
	keywordUse       = "USE"
	keywordUsing     = "USING"
	keywordValue     = "VALUE"
	keywordWaitFor   = "WAITFOR"
	keywordWhen      = "WHEN"
	keywordWhile     = "WHILE"
	keywordWith      = "WITH"
)
