#!/usr/bin/python3

import os
import re
import sys

from extract import get_extracts
from files import dump_yaml
from files import walk
from transform import transform_extract


def main():
  arg = sys.argv[-1]

  if arg == 'help':
    print('Generate stdlib documentation')
    return

  stdlib_path = arg
  stdlib_path = os.path.abspath(stdlib_path)

  representations = {}

  for file in walk(stdlib_path):
    for extract in get_extracts(file, stdlib_path):
      package = extract.token_package

      if not representations.get(package):
        representations[package] = []

      representations[package].append({
        'token': extract.token_name,
        'file_name': extract.file_name,
        'line_number': extract.line_number,
        'doc': transform_extract(extract),
      })

  dump_yaml(representations, 'stdlib-docs-rep.yaml')


if __name__ == '__main__':
  main()
