name: "Static Analysis"

on: [push, pull_request]

jobs:
  analyze:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19'

    - name: Set up linters
      run: make install-tools

    - name: Lint
      run: |
          make vet
          make lint
          make fmt
          git diff
          if [[ $(git diff) != '' ]]; then echo 'Invalid formatting!' >&2; exit 1; fi
